version: '3.2'

services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - "8088:80"
      - "8089:443"
    volumes:
      - "/opt/www/code:/code"
      - "./ssl:/etc/ssl"
      - "./nginx.conf:/etc/nginx/conf.d/site.conf"
      - "/var/log/nginx:/var/log/nginx"
    depends_on:
      - php
    
  php:
    image: php:7-fpm    
    restart: always
    volumes:
      - "./web:/var/www/html"
      - "./log:/var/log/php"